# Generated by Django 2.2.6 on 2020-02-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='age',
            new_name='age_month',
        ),
        migrations.AddField(
            model_name='pet',
            name='age_year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
