# Generated by Django 2.2.6 on 2020-02-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_auto_20200218_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='consultation_fee',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
