# Generated by Django 2.2.6 on 2020-02-19 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_doctor_consultation_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purposeanddiet',
            old_name='set1',
            new_name='diet',
        ),
        migrations.RenameField(
            model_name='purposeanddiet',
            old_name='set2',
            new_name='diet_state',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medicine8',
        ),
    ]
