# Generated by Django 2.2.6 on 2020-02-19 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_auto_20200219_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purposeanddiet',
            name='deworming_purpose',
        ),
        migrations.RemoveField(
            model_name='purposeanddiet',
            name='new_diet',
        ),
        migrations.RemoveField(
            model_name='purposeanddiet',
            name='new_diet_state',
        ),
    ]
