# Generated by Django 2.2.6 on 2020-02-19 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0005_auto_20200219_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccination',
            name='pet',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pet.Pet'),
            preserve_default=False,
        ),
    ]
