# Generated by Django 2.2.6 on 2020-02-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0009_auto_20200221_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=250)),
                ('summery', models.CharField(max_length=500)),
                ('authors', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('published_on', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='books/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Case_Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('published_on', models.DateField()),
                ('link', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Conferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('timings', models.TimeField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Seminars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('timings', models.TimeField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vet_News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('timings', models.TimeField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='testdate',
        ),
    ]
