from django.contrib import admin
from .models import *

# Register your models here.s
admin.site.site_header = 'Aodh Admin'
admin.site.register(Customer)
admin.site.register(Pet)
admin.site.register(PurposeAndDiet)
admin.site.register(Assessment)
admin.site.register(Vitals)
admin.site.register(Deworming)
admin.site.register(Diagnostics)
admin.site.register(Vaccination)
admin.site.register(Prescription)
admin.site.register(Symptoms)
admin.site.register(Doctor)
admin.site.register(Log)
admin.site.register(doctemp)
admin.site.register(Summary_analytics)
admin.site.register(Vaccination_coustmer)
admin.site.register(DoctorLogList)
admin.site.register(DoctorViewLog)
admin.site.register(multipetpayment)
admin.site.register(docip)
admin.site.register(Conferences)
admin.site.register(Seminars)
admin.site.register(Vet_News)
admin.site.register(Articles)
admin.site.register(Case_Reports)
admin.site.register(Book)
admin.site.register(bookmarks_article)
admin.site.register(bookmarks_case_reports)
admin.site.register(bookmarks_conferences)
admin.site.register(bookmarks_vet_news)
admin.site.register(bookmarks_seminars)
admin.site.register(bookmarks_books)
admin.site.register(Vccination_Remainder)
